apiVersion: v1
kind: Pod
metadata:
  name: edge-test
  labels:
    app: edge-test
spec:
  restartPolicy: OnFailure
  containers:
  - name: edge-test
    image: agilenn-edge:v2.0
    securityContext:
      privileged: true
    resource:
      limits:
        cpu: "0.3"
      requests:
        cpu: "0.3"
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    args: ["/bin/bash","-c","tc qdisc add dev eth0 root tbf rate 5mbit burst 12kbit latency 400ms; python edge_inference.py"]
    codePath: usr/symteacher/.edge/agilenn/
    ports:                       
    - containerPort: 98     
      protocol: TCP 
  - name: cloud-test
    image: agilenn-cloud:v2.0
    securityContext:
      privileged: true
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    args: ["/bin/bash","-c","python cloud_inference.py -i 0.0.0.0 -p 99"]
    ports:
    - containerPort: 99
      protocol: TCP
